/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UIadmin;


import info5100.university.example.Department.Department;
import info5100.university.example.Persona.AdmainProfile;
import java.awt.*;
import javax.swing.*;
import info5100.university.example.UIadmin.AdminProfileManagementJPanel;

/**
 *
 * @author 陈凯璐
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private AdmainProfile admainprofile;
    
    private JPanel mainCardLayoutJPanel; 
    private Department department;
  
    public AdminWorkAreaJPanel(JPanel mainCardLayoutJPanel, Department department,AdmainProfile ap) {
        this.mainCardLayoutJPanel = mainCardLayoutJPanel; 
        this.department = department;
        this.admainprofile = ap;
        initComponents();
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageAccounts1 = new javax.swing.JButton();
        btnRegisterPerson1 = new javax.swing.JButton();
        btnManageFaculty1 = new javax.swing.JButton();
        btnManageStudents1 = new javax.swing.JButton();
        btnManageRegistrar1 = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        btnAnalytics1 = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        btnManageAccounts1.setText("Manage User Accounts");
        btnManageAccounts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAccounts1ActionPerformed(evt);
            }
        });

        btnRegisterPerson1.setText("Person Registration");
        btnRegisterPerson1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPerson1ActionPerformed(evt);
            }
        });

        btnManageFaculty1.setText("Manage Faculty");
        btnManageFaculty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFaculty1ActionPerformed(evt);
            }
        });

        btnManageStudents1.setText("Manage Students");
        btnManageStudents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudents1ActionPerformed(evt);
            }
        });

        btnManageRegistrar1.setText("Manage Registrar");
        btnManageRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRegistrar1ActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblTitle1.setText("Admin Work Area");

        btnAnalytics1.setText("Analytics Dashboard");
        btnAnalytics1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalytics1ActionPerformed(evt);
            }
        });

        btnManageProfile.setText("Manage Profile");
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(lblTitle1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageRegistrar1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnRegisterPerson1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnManageAccounts1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(btnManageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnManageStudents1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageFaculty1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnalytics1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTitle1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageAccounts1)
                    .addComponent(btnManageFaculty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterPerson1)
                    .addComponent(btnManageStudents1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageRegistrar1)
                    .addComponent(btnAnalytics1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProfile)
                    .addComponent(btnLogOut))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAccounts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAccounts1ActionPerformed
        // TODO add your handling code here:
        AdminManageUserAccountsJPanel panel = new AdminManageUserAccountsJPanel(department, mainCardLayoutJPanel);
        mainCardLayoutJPanel.add("AdminManageUserAccountsJPanel", panel);
        CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
        layout.show(mainCardLayoutJPanel, "AdminManageUserAccountsJPanel");
       
    }//GEN-LAST:event_btnManageAccounts1ActionPerformed

    private void btnManageFaculty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFaculty1ActionPerformed
        // TODO add your handling code here:
        AdminManageFacultyJPanel panel = new AdminManageFacultyJPanel(department, mainCardLayoutJPanel);
        panel.populateTable(); 
        mainCardLayoutJPanel.add("AdminManageFacultyJPanel", panel);
        CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
        layout.show(mainCardLayoutJPanel, "AdminManageFacultyJPanel");
    }//GEN-LAST:event_btnManageFaculty1ActionPerformed

    private void btnRegisterPerson1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPerson1ActionPerformed
        // TODO add your handling code here:
        AdminPersonRegistrationJPanel personRegPanel =
            new AdminPersonRegistrationJPanel(mainCardLayoutJPanel, department);

         mainCardLayoutJPanel.add("AdminPersonRegistrationJPanel", personRegPanel);
         CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
         layout.show(mainCardLayoutJPanel, "AdminPersonRegistrationJPanel");
    }//GEN-LAST:event_btnRegisterPerson1ActionPerformed

    private void btnManageRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRegistrar1ActionPerformed
        // TODO add your handling code here:
        AdminManageRegistrarJPanel panel = new AdminManageRegistrarJPanel(department, mainCardLayoutJPanel);
         panel.populateTable(); 
         mainCardLayoutJPanel.add("AdminManageRegistrarJPanel", panel);
         CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
         layout.show(mainCardLayoutJPanel, "AdminManageRegistrarJPanel");
    }//GEN-LAST:event_btnManageRegistrar1ActionPerformed

    private void btnManageStudents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudents1ActionPerformed
        // TODO add your handling code here:
         AdminManageStudentsJPanel panel = new AdminManageStudentsJPanel(department, mainCardLayoutJPanel);
         panel.populateTable(); 
         mainCardLayoutJPanel.add("AdminManageStudentsJPanel", panel);
         CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
         layout.show(mainCardLayoutJPanel, "AdminManageStudentsJPanel");
    }//GEN-LAST:event_btnManageStudents1ActionPerformed

    private void btnAnalytics1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalytics1ActionPerformed
        // TODO add your handling code here:
         AdminAnalyticsDashboardJPanel panel = new AdminAnalyticsDashboardJPanel(department, mainCardLayoutJPanel);
         mainCardLayoutJPanel.add("AdminAnalyticsDashboardJPanel", panel);
         CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
         layout.show(mainCardLayoutJPanel, "AdminAnalyticsDashboardJPanel");
    }//GEN-LAST:event_btnAnalytics1ActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        AdminProfileManagementJPanel panel = new AdminProfileManagementJPanel(mainCardLayoutJPanel, department, admainprofile);
        mainCardLayoutJPanel.add("AdminProfileManagementJPanel", panel);
        CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
        layout.show(mainCardLayoutJPanel, "AdminProfileManagementJPanel");
    }//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) mainCardLayoutJPanel.getLayout();
        mainCardLayoutJPanel.remove(this); 
        layout.show(mainCardLayoutJPanel, "Log");
    }//GEN-LAST:event_btnLogOutActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageAccounts1;
    private javax.swing.JButton btnManageFaculty1;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnManageRegistrar1;
    private javax.swing.JButton btnManageStudents1;
    private javax.swing.JButton btnRegisterPerson1;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
