/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UIadmin;

import info5100.university.example.Department.Department;
import info5100.university.example.Persona.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 陈凯璐
 */
public class AdminAnalyticsDashboardJPanel extends javax.swing.JPanel {
    
    private Department department;

    /**
     * Creates new form AdminAnalyticsDashboardJPanel
     */
    public AdminAnalyticsDashboardJPanel(Department department) {
        this.department = department;
        initComponents();
        populateSummaryTable();
    }

    private void populateSummaryTable() {
    DefaultTableModel model = (DefaultTableModel) tblSummary.getModel();
    model.setRowCount(0);
    
    int totalStudents = 0;
    int totalFaculty = 0;
    int totalRegistrar = 0;
    int totalAdmin = 0;

    if (department.getUseraccountdirectory() != null) {
        for (UserAccount ua : department.getUseraccountdirectory().getUserAccountDirectory()) {
            String role = ua.getRole().toLowerCase();
            if (role.contains("student")) totalStudents++;
            else if (role.contains("faculty")) totalFaculty++;
            else if (role.contains("registrar")) totalRegistrar++;
            else if (role.contains("admin")) totalAdmin++;
        }
    }

    int totalCourses = (department.getCoursecatalog() != null)
            ? department.getCoursecatalog().getCourseList().size()
            : 0;

    int totalEnrolledStudents = (department.getStudentdirectory() != null)
            ? department.getStudentdirectory().getStudentlist().size()
            : 0;

    double totalTuitionRevenue = 0.0;

    if (department.getStudentdirectory() != null) {
        for (StudentProfile sp : department.getStudentdirectory().getStudentlist()) {
            ArrayList<PaymentTransaction> transactions = sp.getPaymentHistory();
            if (transactions != null) {
                for (PaymentTransaction tx : transactions) {
                    if (tx.getAmount() > 0) {
                        totalTuitionRevenue += tx.getAmount();
                    }
                }
            }
        }
    }

    model.addRow(new Object[]{"Student", totalStudents, totalEnrolledStudents, 0});
    model.addRow(new Object[]{"Faculty", totalFaculty, totalFaculty, 0});
    model.addRow(new Object[]{"Registrar", totalRegistrar, totalRegistrar, 0});
    model.addRow(new Object[]{"Admin", totalAdmin, totalAdmin, 0});
    model.addRow(new Object[]{"Total Tuition Revenue", "-", "-", "$" + String.format("%,.2f", totalTuitionRevenue)});

    lblTotalUsersValue.setText(String.valueOf(totalStudents + totalFaculty + totalRegistrar + totalAdmin));
    lblTotalCoursesValue.setText(String.valueOf(totalCourses));
    lblTotalStudentsValue.setText(String.valueOf(totalEnrolledStudents));
    lblTuitionRevenueValue.setText("$" + String.format("%,.2f", totalTuitionRevenue));

    tblSummary.revalidate();
    tblSummary.repaint();

    System.out.println("Dashboard refreshed successfully!");
    System.out.println("Total Tuition Revenue = $" + String.format("%,.2f", totalTuitionRevenue));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTotalUsers = new javax.swing.JLabel();
        lblTotalCourses = new javax.swing.JLabel();
        lblTotalStudents = new javax.swing.JLabel();
        lblTuitionRevenue = new javax.swing.JLabel();
        lblTotalUsersValue = new javax.swing.JLabel();
        lblTotalCoursesValue = new javax.swing.JLabel();
        lblTotalStudentsValue = new javax.swing.JLabel();
        lblTuitionRevenueValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSummary = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblTitle.setText("University Analytics Dashboard");

        lblTotalUsers.setText("Total Active Users");

        lblTotalCourses.setText("Total Courses Offered");

        lblTotalStudents.setText("Total Enrolled Students");

        lblTuitionRevenue.setText("Total Tuition Revenue");

        lblTotalUsersValue.setText("0");

        lblTotalCoursesValue.setText("0");

        lblTotalStudentsValue.setText("0");

        lblTuitionRevenueValue.setText("$0");

        tblSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Role", "Total Users", "Active", "Inactive"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSummary);

        btnRefresh.setText("Refresh Data");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBack.setText(">>Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTotalUsers)
                                .addComponent(lblTotalCourses)
                                .addComponent(lblTotalStudents))
                            .addComponent(lblTuitionRevenue))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTuitionRevenueValue, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTotalUsersValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalCoursesValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTotalStudentsValue, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addGap(3, 3, 3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnRefresh)
                        .addGap(82, 82, 82)
                        .addComponent(btnBack)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalUsers)
                    .addComponent(lblTotalUsersValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCourses)
                    .addComponent(lblTotalCoursesValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalStudents)
                    .addComponent(lblTotalStudentsValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTuitionRevenue)
                    .addComponent(lblTuitionRevenueValue))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnBack))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        System.out.println("Refresh button clicked!"); 
        populateSummaryTable(); 
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Container parent = this.getParent();
    if (parent.getLayout() instanceof CardLayout) {
        CardLayout layout = (CardLayout) parent.getLayout();
        layout.previous(parent);
    }
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCourses;
    private javax.swing.JLabel lblTotalCoursesValue;
    private javax.swing.JLabel lblTotalStudents;
    private javax.swing.JLabel lblTotalStudentsValue;
    private javax.swing.JLabel lblTotalUsers;
    private javax.swing.JLabel lblTotalUsersValue;
    private javax.swing.JLabel lblTuitionRevenue;
    private javax.swing.JLabel lblTuitionRevenueValue;
    private javax.swing.JTable tblSummary;
    // End of variables declaration//GEN-END:variables
}
