/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UIstudent;

import info5100.university.example.Department.Department;
import info5100.university.example.Persona.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sunzuolin
 */
public class ProfileManagement extends javax.swing.JPanel {
JPanel mainpanel;
Department department;
StudentProfile studentprofile;
    /**
     * Creates new form ProfileManagement
     */
    public ProfileManagement(JPanel mainpanel,Department department,StudentProfile studentprofile) {
        initComponents();
        this.mainpanel=mainpanel;
        this.department=department;
        this.studentprofile = studentprofile;
        refreshTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtuseraccount = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Profile Management");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel3.setText("StudentID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel4.setText("UserAccount");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 140, -1));
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 140, -1));
        add(txtuseraccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 140, -1));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 140, -1));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) mainpanel.getLayout();
        layout.previous(mainpanel);
        mainpanel.remove(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = txtname.getText();
        int id;
        id = Integer.parseInt(txtid.getText());
        String username = txtuseraccount.getText();
        String password = txtpassword.getText();
        studentprofile.getPerson().setName(name);
        studentprofile.setStudentID(id);
        department.getUseraccountdirectory().findUserAccount(name).setUserName(username);
        department.getUseraccountdirectory().findUserAccount(name).setUserPassword(password);
        JOptionPane.showMessageDialog(null, "Update successfully", "information",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private void refreshTextField() {
       txtname.setText(studentprofile.getPerson().getName());
       txtid.setText(String.valueOf(studentprofile.getStudentID()));
       txtuseraccount.setText(department.getUseraccountdirectory().findUserAccount(studentprofile.getPerson().getName()).getUserLoginName());
       txtpassword.setText(department.getUseraccountdirectory().findUserAccount(studentprofile.getPerson().getName()).getUserPassword());   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtuseraccount;
    // End of variables declaration//GEN-END:variables
}
