/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UIstudent;

import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunzuolin
 */
public class TranscriptReview extends javax.swing.JPanel {
JPanel mainpanel;
Department department;
StudentProfile studentprofile;
    /**
     * Creates new form TranscriptReview
     */
    public TranscriptReview(JPanel mainpanel,Department department,StudentProfile studentprofile) {
        initComponents();
        this.mainpanel=mainpanel;
        this.department=department;
        this.studentprofile = studentprofile;
        overallgpa.setText(String.valueOf((double)studentprofile.getTranscript().getStudentTotalScore()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ComboBox3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtas = new javax.swing.JTextField();
        termgpa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        overallgpa = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        ComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025Spring", "2025Summer", "2025Fall", "2025Winter", " " }));
        ComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox3ActionPerformed(evt);
            }
        });
        add(ComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Transcript");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CourseID", "CourseName", "Grade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 50, 560, 240));

        jLabel2.setText("Academic Standing");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel3.setText("Term GPA Points");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
        add(txtas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 140, -1));
        add(termgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 140, -1));

        jLabel4.setText("Overall GPA Points");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));
        add(overallgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) mainpanel.getLayout();
        layout.previous(mainpanel);
        mainpanel.remove(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox3ActionPerformed
        // TODO add your handling code here:
        String selectedsemster = (String) ComboBox3.getSelectedItem().toString();
        populateTable1(selectedsemster);
    }//GEN-LAST:event_ComboBox3ActionPerformed
    private void populateTable1(String selectedsemster) {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        CourseLoad courseload = studentprofile.getCourseLoadBySemester(selectedsemster);
        for(  SeatAssignment sa : courseload.getSeatAssignments()){ 
           Object[] row = new Object[4];
           row[0] = sa.getCourseOffer().getCourseNumber();
           row[1] = sa.getCourseOffer().getCourseName();
           row[2] = sa.convertToGPA(sa.getScore());
         
          model.addRow(row);
        }
        termgpa.setText(String.valueOf((double) courseload.getqualitypoints() / courseload.gettotalhours()));
        txtas.setText(courseload.convertToLetter(courseload.getqualitypoints() / courseload.gettotalhours()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField overallgpa;
    private javax.swing.JTextField termgpa;
    private javax.swing.JTextField txtas;
    // End of variables declaration//GEN-END:variables
}
